### ISSUE TITLE
Webpack Compatibility

### ISSUE THREAD

**Issue by moritzvieli** [bthurlow/nativescript-imagecropper#15]
This plugin does not work with webpack. The issue is described here:
https://github.com/NativeScript/nativescript-dev-webpack/issues/8

-> As a workaround, we removed "use strict" and the __export in the beginning manually.

**Comment by rsaf** [comment]
I'm having the same error related to the nativescript-imagecropper module (version: 0.0.7), while building with webpack and aot.  [https://github.com/NativeScript/nativescript-dev-webpack/issues/16 ](https://github.com/NativeScript/nativescript-dev-webpack/issues/16 )
When I comment out all imagecroppring code in my app, and delete the platform folder, the error goes away.

Any fix for this? 

Also, in your package.json, having "main": "imagecropper.js", instead of "main": "imagecropper", is throwing a compile error.

**Comment by bthurlow** [comment]
Sell pull#6
