### ISSUE TITLE
can you please tell me how to use the cancel

### ISSUE THREAD

**Issue by goodgood-study** [bthurlow/nativescript-imagecropper#38]
i want to konw if i don‘t want to save the change of the picture , i press the cancel,and i want to write some
code for the cancel,  how i need to do,can you show me?

**Comment by shiv19** [comment]
When user cancels the action, the promise is rejected. Just handle it there

**Comment by jiangzhuofan** [comment]
but i use it with a image-picker,the function like that i use image-picker to select the picture as my Chat Heads ,and the image-cropper to change the chat heads size. but the problem is that  i choose the new picture,but i want to do anything,i press cancel.  as a result it will be use the old picture but actually it use the new one.so i want to know how to do some codeing with the cancel function.   i don't know can you understand me.

**Comment by shiv19** [comment]
Can you check if the code inside the catch block executes when you cancel the operation?

**Comment by shiv19** [comment]
No, all your code for success flow should be in then block, and code for failure flow in catch block.
Make sure you're not doing anything outside of it

**Comment by jiangzhuofan** [comment]
I want to find how to make some code inside the method of cancel...but I don't know how to do，can you tell me

**Comment by jiangzhuofan** [comment]
Hello,Shiva,do you have a ins or a facebook.Can i Follow your account.

**Comment by shiv19** [comment]
All my social links are listed in the footer of my website. shiv19.com
